use_frameworks!
platform :ios, '9.0'

target 'TestTask3' do
    pod 'ObjectMapper', '3.1.0'
    pod 'RxSwift', '4.1.2'
    pod 'RxDataSources', '3.0.2'
    pod 'Alamofire', '4.7.1'
    pod 'SwiftyJSON', '4.0.0'
end
